import type { NextPage } from "next";
import { getFontDefinitionFromManifest } from "next/dist/server/font-utils";
import Head from "next/head";
import { useEffect } from "react";
import * as THREE from "three";
const Home: NextPage = () => {
  useEffect(() => {
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(
      75,
      window.innerWidth / window.innerHeight,
      0.1,
      1000
    );
    const renderer = new THREE.WebGL1Renderer({
      canvas: document.querySelector("#ez") as Element,
    });
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(window.innerWidth, window.innerHeight);
    camera.position.setZ(30);
    const geometry = new THREE.TorusGeometry(10, 3, 16, 100);
    const material = new THREE.MeshBasicMaterial({
      color: 0xff6347,
      wireframe: true,
    });
    const torus = new THREE.Mesh(geometry, material);
    scene.add(torus);

    function animate() {
      requestAnimationFrame(animate);
      torus.rotation.x += 0.01;
      renderer.render(scene, camera);
    }
    animate();
  }, []);

  return (
    <>
      <Head>
        <title>Three - wiktrek.xyz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <canvas id="ez"></canvas>
      </main>
    </>
  );
};

export default Home;
